import { Inter } from 'next/font/google'

import { AppSidebar } from '../components/app-sidebar'
import { SidebarInset, SidebarProvider } from '../components/ui/sidebar'
import './globals.scss'
import AppHeader from '../components/app-header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset className="flex flex-col h-full">
            <AppHeader />
            <div className="flex-1">{children}</div>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  )
}
